### ISSUE TITLE
Заказ: группировать заявки по их автору

### ISSUE THREAD

**Issue by vitalk** [yandex-shri-minsk-2016/yummy-time#132]
Так как любой человек может подать несколько заявок в заказ, то при отображении их на странице заказа их нужно группировать по автору, чтобы избежать дублирования информации.

**Comment by octocrux** [comment]
А нужно ли нам вообще давать возможность человеку добавлять несколько заявок в заказ? Почему не редактировать уже существующую?

**Comment by vitalk** [comment]
Как и говорил, это довольно не удобно для конечного пользователя, т.к. ему нужно самому пересчитывать сумму и править текст. Вместе с #139 такой вариант будет более удобным.
