### ISSUE TITLE
Оповещения: добавить механизм оповещения пользователей

### ISSUE THREAD

**Issue by octocrux** [yandex-shri-minsk-2016/yummy-time#137]
Необходимо настроить механизмы оповещения участников заказа о происходящих событиях (время собирать деньги, еда доставлена, проблемы с доставкой и пр.). Реализовать один из вариантов (или несколько). По ссылкам - варианты сторонних сервисов, которыми можно воспользоваться:
- [по почте](https://www.mailgun.com/)
- [через sms]( https://www.twilio.com/)

**Comment by vitalk** [comment]
> Mailgun

👍
