### ISSUE TITLE
Оформление заказа: создать шаблон страницы

### ISSUE THREAD

**Issue by octocrux** [yandex-shri-minsk-2016/yummy-time#16]
Определить и реализовать необходимый набор блоков для следующих элементов страницы:
- [ ] Список участников заказа
- [ ] Панель для отображения элемента списка
- [ ] Форма оповещения участников заказа
- [ ] Используя реализованные блоки, сверстать шаблон страницы
- [ ] Определить начальные стили (необходимо только грубое соответствие макету)

См. компоненты приложения, отдельные необходимые блоки могут быть уже реализованы. Для именования блоков используется [БЭМ-методология](https://ru.bem.info/method/).

Макет страницы:
![order_summary](https://cloud.githubusercontent.com/assets/2687551/14426510/2e6aa3b6-fff8-11e5-9fb1-7e76d898c9ae.jpg)

**Comment by vitalk** [comment]
Не думаю что «Форма оповещения участников заказа» сейчас нужна. И не совсем понятно назначение кнопки «Деньги»

\cc @octocrux
