### ISSUE TITLE
Настроить линтер

### ISSUE THREAD

**Issue by octocrux** [yandex-shri-minsk-2016/yummy-time#20]
Настроить инструмент контроля качества кода. Если не ошибаюсь, мы остановились на ESLint.
- [x] Установить пакет
- [x] Добавить файлы конфигурации
- [x] Определить начальный набор правил

**Comment by Evvik** [comment]
fixed via [https://github.com/yandex-shri-minsk-2016/yummy-time/pull/70](https://github.com/yandex-shri-minsk-2016/yummy-time/pull/70)
