### ISSUE TITLE
Схема данных

### ISSUE THREAD

**Issue by vitalk** [yandex-shri-minsk-2016/yummy-time#26]
Я так себе представляю более-менее цельную модель данных в приложении и их связи

- [Служба доставки](https://gist.github.com/vitalk/761c0081b2cab667ce7be931c296cab8#file-food-services-json)

- [Список доступных продуктов/товаров](https://gist.github.com/vitalk/761c0081b2cab667ce7be931c296cab8#file-food-menu-json)

- [Выбранный товар](https://gist.github.com/vitalk/761c0081b2cab667ce7be931c296cab8#file-purchase-json)

- [Пользователь](https://gist.github.com/vitalk/761c0081b2cab667ce7be931c296cab8#file-person-json)

---
Я бы уже начинал прикручивать авторизацию, чтобы исключить постоянное дублирование многих пунктов (например, данные об ответственном за заказ можно смело брать из его профиля, также как и информацию о том кто добавил новую заявку (#13)).

**Comment by criyology** [comment]
Виталик, а сделай плиз в корне папку doc — и залей туда все вот эти вот соображения в виде .md и .json файлов.
Это лучше, чем вики, так как у вас докумментация будет версионироваться вместе с кодом.
