### ISSUE TITLE
Добавить эндпоинт для регистрации

### ISSUE THREAD

**Issue by octocrux** [yandex-shri-minsk-2016/yummy-time#36]

**Comment by criyology** [comment]
По правилам игры надо использовать Яндекс.Паспорт:
https://tech.yandex.ru/oauth/

**Comment by criyology** [comment]
То есть, вместо формы логина будет редирект на паспорт. Туда же и за регистрацией. Потом можно будет припилить всякие логины по фейсбуку, твиттору и гуглу.
