### ISSUE TITLE
База данных: структура документа

### ISSUE THREAD

**Issue by octocrux** [yandex-shri-minsk-2016/yummy-time#38]
Нужно попробовать разные стратегии организации данных в документах.
- [ ] Выбрать, что лучше: вложенные документы или ссылки на внешние документы
- [ ] Определиться, нужно ли хранить ссылки на `orders` и `portions` в документе `account`

**Comment by vitalk** [comment]
- Т.к. вопрос производительности перед нами сейчас не стоит, то я бы делал ссылки. Они позволят нам упростить синхронизацию изменений в документах, а иначе придётся писать отдельную логику на это

- Я теперь не вижу проблем при создании связей один ко многим (#97), то наверное удобней будет добавить к аккаунту список его заказов и заявок.
