### ISSUE TITLE
Синхронизировать форму новой заявки с текущей схемой данных

### ISSUE THREAD

**Issue by octocrux** [yandex-shri-minsk-2016/yummy-time#43]
- [ ] Поправить модель
- [ ] Поправить разметку
- [ ] Поправить стили
- [ ] Настроить эндпоинт

**Comment by Evvik** [comment]
closed via [https://github.com/yandex-shri-minsk-2016/yummy-time/pull/44](https://github.com/yandex-shri-minsk-2016/yummy-time/pull/44)

**Comment by vitalk** [comment]
О чём здесь вообще идет речь?
