### ISSUE TITLE
Новая заявка

### ISSUE THREAD

**Issue by vitalk** [yandex-shri-minsk-2016/yummy-time#56]
Сейчас мы заставляем того кто подаёт заявку самого считать какая у него вышла **итоговая сумма** (#13), хотя мы это можем и сами посчитать. Поясните мне почему мы не добавляем заявки по одной на продукт? 

Мой сценарий такой

- хочу пиццу
- добавил её в заказ и указал её цену (сейчас у нас нет списка доступных продуктов, поэтому вводим всё сами)
- хочу кефир
- добавил его в заказ и указал цену на кефир
- итого вижу сколько я должен (пицца + кефир)

Причём, чем больше человек добавляет различных продуктов в заказ, тем сложней ему самому всё считать.

**Comment by Rei-li** [comment]
Насколько понимаю, так происходит сейчас именно потому, что мы не обсуждали сам продукт и он не добавляется. На мой взгляд, то, что ты предлагаешь, должно происходить при добавлении продукта в заявку. У продукта есть цена, и при добавлении его в заявку должна была бы считаться общая стоимость заявки. Но мы так упростили, что пишем заявку текстом и соответственно считаем все сами. Т.е. твой сценарий, это добавление продукта в заявку, когда они появятся, зачем делать заявку на каждый продукт?

**Comment by vitalk** [comment]
> Но мы так упростили, что пишем заявку текстом...

да, мы упростили, но только пока не выбираем из доступных продуктов

> и соответственно считаем все сами

вот это мне и не понятно. Если можно по очереди добавить в заказ всё что ты хочешь, с указанием цены на конкретный продукт, а итоговая сумма посчитается автоматически. Зачем застовлять человека самому считать эту сумму?

Наше упрощение остаётся – в тексте ты пишешь что ты хочешь заказать (т.к. у нас нет списка продуктов), но логика работы такая как и со списком продуктов. Добавил продукт – указал на него цену – итоговая сумма увеличилась.

---
Оба варианта одинаковы при добавлении только одного предмета в заказ.

**Comment by Rei-li** [comment]
>  но логика работы такая как и со списком продуктов. Добавил продукт – указал на него цену – итоговая сумма увеличилась

Со списком продуктов ты вообще цену добавлять не будешь, она должна быть в продукте забита. Заявка формируется от каждого участника, участник добавляет в заявку продукты. У каждого продукта есть цена. При добавлении продукта в заявку увеличивается цена заявки. При увеличении цены заявки увеличивается цена заказа. Так у тебя сразу подсчитана сумма по каждому участнику. Зачем делать заявку на каждый продукт продукт?

**Comment by vitalk** [comment]
т.е. в конечном виде ты хочешь такую вложеность?

```
- заказ
  - заявка
     - продукт
     - продукт
```

я себе это проще представлял

```
- заказ
  - продукт
  - продукт
```

Дополнительный уровень вложенности вносит дополнительную сложность.

**Comment by Rei-li** [comment]
Т.е. ты предлагаешь  что-то типа :
- заказ
    - заявка
         - пользователь
         -  название продукта (не ссылка на него)
         - цена
         -  комментарий (по каждому продукту, не по всей заявке)
    - заявка
         - пользователь (может быть тот же самый)
         -  название продукта (не ссылка на него)
         - цена
         -  комментарий (по каждому продукту, не по всей заявке)

а в списке у тебя будет опять же продукт с названием и ценой



Вместо варианта с заявкой:
 - заказ
    - заявка 
           - пользователь
           -  общий комментарий
           - [продукты]

где продукт - это что-то общее для списка в заявке и в общем списке для выбора, а заявка создается от конкретного пользователя

Так?

**Comment by vitalk** [comment]
Нет, я никогда не считал `заявку` отдельной сущностью.

Вообще мы отклонились от моего первоначального вопроса

> Зачем мы заставляем того кто подаёт заявку самого считать какая у него вышла итоговая сумма

**Comment by Rei-li** [comment]
Нет, мы не отклонились, т.к. ответ зависит от того как ты представляешь себе конечную схему. В случае с ценой забитой в продукт, вроде как ясно, что пока не реализованы продукты, ты считаешь сам, когда будут продукты, считать не будешь

**Comment by vitalk** [comment]
> как ты представляешь себе конечную схему

в субботу более-менее определились, она даже в репозитории есть

- [заказ](https://github.com/yandex-shri-minsk-2016/yummy-time/blob/master/docs/order.json)
  - [продукт/порция](https://github.com/yandex-shri-minsk-2016/yummy-time/blob/master/docs/portion.json)

> пока не реализованы продукты, ты считаешь сам

я не вижу связи, зачем мне считать самому **итоговую** сумму, если её можно посчитать  автоматически

**Comment by Rei-li** [comment]
> продукт/порция

ну я видимо в субботу упустила что-то, мы вроде не говорили, что порция это то же самое, что продукт, просто продукты решено было пока не добавлять, соответственно и не обсуждать. Соответственно  пока ты в заявке указываешь текстом все продукты какие хочешь, ты и итоговую сумму пишешь, когда начнешь добавлять по продукту, то и цена с ними придет, и вписывать ты ничего не будешь, все посчитается автоматически

**Comment by vitalk** [comment]
> мы вроде не говорили, что порция это то же самое

это не тоже самое, но т.к. мы продукты отложили, а заказы оформлять нужно, то логично смержить их вместе для начала

> ты в заявке указываешь текстом все продукты какие хочешь, ты и итоговую сумму пишешь

вот мы и вернулись к самому началу :D Не лучше ли добавлять продукты в заказ по одному, тогда сумма будет считаться автоматически даже сейчас (без продуктов).

**Comment by Rei-li** [comment]
> Не лучше ли добавлять продукты в заказ по одному

мне не нравится, теряется смысл заявки как объединяющей сущности по участнику

**Comment by octocrux** [comment]
> Сейчас мы заставляем того кто подаёт заявку самого считать какая у него вышла итоговая сумма (#13), хотя мы это можем и сами посчитать. Поясните мне почему мы не добавляем заявки по одной на продукт?

Добавление продукта в заявку - это усложнение, которое выходит за рамки начальной версии приложения.
Начальная версия приложения (это еще даже не MVP) предполагает возможность пройти весь путь от "хочу есть" до "я покушал" с реализацией минимума функциональности.
Предполагалось, что пользователь делает от своего имени одну заявку и описывает в ней все, что хочет добавить к общему заказу.

> Если можно по очереди добавить в заказ всё что ты хочешь

В **заказ** можно добавлять только **заявки**. Мы пока опускаем сценарий, где пользователь имеет возможность добавлять в заявку продукты из какого-то списка. Поэтому - просто два текстовых поля.

> в субботу более-менее определились, она даже в репозитории есть
* заказ
      * продукт/порция

**Заявка = порция = portion**. Описывает все, что хочет отдельно взятый человек добавить к общему заказу.
**Продукт != порция**. Продукт - это описание конкретной позиции, предложенной рестораном, и он пока не реализован.

В заявке можно указать в текстовом поле "заказ" все, что хочется покушать, и в текстовом поле "сумма" - сколько это будет стоить.
