### ISSUE TITLE
Оформление: внешний вид приложения

### ISSUE THREAD

**Issue by octocrux** [yandex-shri-minsk-2016/yummy-time#68]
Идеи внешнего вида компонентов приложения

**Comment by IvanBisultanov** [comment]
http://www.grocerygateway.com/app/img/iphone_main.png
http://ww1.prweb.com/prfiles/2011/02/28/8170403/iPad%20Home%20Screen%20Shot.JPG
http://anareyna.com/wp-content/uploads/2015/02/MinimusV9-4.jpg
https://d13yacurqjgara.cloudfront.net/users/479167/screenshots/2119906/portfolio.png
