### ISSUE TITLE
Развернуть приложение на Heroku

### ISSUE THREAD

**Issue by octocrux** [yandex-shri-minsk-2016/yummy-time#75]

**Comment by vitalk** [comment]
Что ты для mongo использовала? Я вот наткнулся на [mlab](https://mlab.com/)

**Comment by octocrux** [comment]
На данный момент:
* есть база данных в mlab
* развернута [серверная часть](https://yummy-server.herokuapp.com/) приложения, привязана к базе (ветка `prod-server`)
* развернута [клиентская часть](https://yummy-time.herokuapp.com), но не получается проксировать запросы на сервер (ветка `prod-client`)

Выдает:
```
vendor-8fe2fb0….js:3 POST https://yummy-time.herokuapp.com/auth/token 405 (Not Allowed)
```
<img width="552" alt="screen shot 2016-05-11 at 03 45 34" src="https://cloud.githubusercontent.com/assets/2687551/15166815/42b7ee06-172b-11e6-84a2-8bcb94339407.png">

Запущенное на локальной машине приложение без проблем общается с сервером и базой данных.
Использую [heroku-buildpack-ember-cli](https://github.com/tonycoco/heroku-buildpack-ember-cli),
переменные среды API_URL и API_PREFIX_PATH установлены
