### ISSUE TITLE
Заказ: обновление статуса

### ISSUE THREAD

**Issue by octocrux** [yandex-shri-minsk-2016/yummy-time#83]
На странице оформления заказа при нажатии на кнопку "сформировать" должен обновляться статус заказа `active`.

**Comment by vitalk** [comment]
> должен обновляться статус заказа active.

Ты имеешь ввиду, что после формирования заказа никто не может в него ничего добавить/удалить?

Просто моём представлении статус заказа это и то сколько денег собрано/нужно на текущий момент.

**Comment by octocrux** [comment]
В модели заказа у нас есть поле - `active`, которое указывает на возможность добавления заявок в заказ. Это поле должно принимать значение `false` при нажатии на кнопку формирования заказа.

**Comment by vitalk** [comment]
Т.е. никакой другой логики кроме запрета добавления новых заявок кнопка «сформировать заказ» не несёт?

**Comment by vitalk** [comment]
Когда и на каком экране мы должны просмотреть всю информацию о заказе, чтобы его заказать (т.е. набрать номер телефона и продиктовать что нам навыбирали голодные люди)?

**Comment by octocrux** [comment]
> Т.е. никакой другой логики кроме запрета добавления новых заявок кнопка «сформировать заказ» не несёт?

Мы еще обсуждали рассылку уведомлений участникам: организатор нажал кнопку - новые участники добавиться не могут, остальным (всем, либо тем, кто деньги еще не принес) приходит уведомление вида "пора оформлять заказ, `Вася` ждет оплаты в `к.205`". Этим занимается @Rei-li 
#98 - следующий этап задачи.

> Когда и на каком экране мы должны просмотреть всю информацию о заказе

В субботу речь шла о том, что на странице `orders/:id/checkout` нам будут доступны два view, на одном из которых будет список участников и их долгов (там же чекбоксы для подтверждения оплаты), на другом - детальное содержание их заявок и комментарии. Второй view вполне подходит для просмотра информации во время заказа по телефону.

**Comment by vitalk** [comment]
> на странице orders/:id/checkout нам будут доступны два view

хорошо, я тоже так думаю
