### ISSUE TITLE
Заказ: обязательные поля

### ISSUE THREAD

**Issue by octocrux** [yandex-shri-minsk-2016/yummy-time#86]
Запретить добавлять заказ с незаполненными полями.

**Comment by vitalk** [comment]
Тут два варианта развития событий

- простой - мы помечаем инпуты как `required`
- правильный - мы прикручиваем валидацию на клиент. Тут нужно посмотреть существующие решения и выбрать то что приглянётся.

**Comment by octocrux** [comment]
Сделаем правильно :)
