### ISSUE TITLE
Валидация данных на клиенте

### ISSUE THREAD

**Issue by vitalk** [yandex-shri-minsk-2016/yummy-time#92]
В связи с #86 нужно посмотреть существующие решения и выбрать то что приглянётся. Валидация нужна для следующих форм:

- [x] логин
- [x] регистрация
- [x] создание заказа (#143, #144)
- [x] создание заявки к заказу

**Comment by octocrux** [comment]
https://www.npmjs.com/package/validator
Думаю, это то, что нужно.

**Comment by Evvik** [comment]
зачем? какие типы полей мы будем проверять и какие условия для проверки?

**Comment by vitalk** [comment]
> какие типы полей мы будем проверять и какие условия для проверки? смысл подключать плагин?

Для начала немного (почта, место доставки, описание заявки и цена), но всё равно особого смысла всё писать руками не вижу.

Ещё в ember есть встроенный механизм для работы с ошибками - [DS.Errors](http://emberjs.com/api/data/classes/DS.Errors.html)

**Comment by octocrux** [comment]
> какие типы полей мы будем проверять

Проверять умеет только строки.

Навскидку:
- пустые поля
- почту
- телефон
- пароль

**Comment by Evvik** [comment]
пустые поля - length > 0
e-mail - regexp
телефон - regex (определиться с маской)
пароль - length > 0

**Comment by Evvik** [comment]
и также проверка на required

**Comment by octocrux** [comment]
> Ещё в ember есть встроенный механизм для работы с ошибками - DS.Errors

Ember на него ворчит, не могу понять, зачем и почему:

```
WARNING: Interacting with a record errors object will no longer change the record state.
```

**Comment by octocrux** [comment]
@Evvik , я в целом не прочь изобрести велосипед. Но в плагине все давно проверено и оттестировано, а с самодельными валидаторами предвкушаю танцы.

**Comment by Evvik** [comment]
:) думаю будет как раз наоборот

**Comment by criyology** [comment]
Забыли проверять email (он же логин) на уникальность.
Но не кажется ли, что если будет внешний логин, то не будет проблемы с валидацией? Единственное что надо проверять — это то что пользователь хочет сделать пустую заявку. Это «проверяется» блокировкой кнопки sumbit

**Comment by vitalk** [comment]
> Забыли проверять email (он же логин) на уникальность.

Это юрисдикция сервера, тут речь в основном о валидации на клиенте
