### ISSUE TITLE
Заказ: логика работы

### ISSUE THREAD

**Issue by vitalk** [yandex-shri-minsk-2016/yummy-time#99]
В списке заказов мы показываем сколько денег собрано/нужно собрать для того или иного заказа. Таким образом сторонний наблюдатель может легко оценить состояние этого заказа и выбрать подходящий для себя.

- При создании заказа необходимая сумма для заказа берётся из данных поставщика `minOrderCost`

- При добавлении заявок в заказ она (необходимая сумма) будет увеличиваться, но только с того момента, как сумма заявок превысит минимальную сумму заказа.

- При погашении задолженности автором заявки (#81), собранная сумма увеличавается

- Заказ можно оформить только когда `собранная сумма == необходимой сумме` и `необходимая сумма >= минимальной суммы` заказа у этого поставщика

**Comment by octocrux** [comment]
Чтобы не запутываться:
`Минимальная сумма` = `minOrderCost`, минимальная сумма заказа
`Сумма заказа` = сумма всех включенных в заказ заявок
`Собранная сумма` = сумма оплаченных заявок, участвующих в заказе

> При добавлении заявок в заказ она (необходимая сумма) будет увеличиваться

Если здесь речь о минимальной сумме, то зачем ее увеличивать? Это будет вводить в заблуждение участников заказа.

> Заказ можно оформить только когда собранная сумма == необходимой сумме и необходимая сумма >= минимальной суммы

Думаю, с наложением ограничений на действия пользователя стоит подождать хотя бы до тех пор, пока не будет реализована возможность удаления заявок из заказа

**Comment by vitalk** [comment]
> Если здесь речь о минимальной сумме, то зачем ее увеличивать?

минимальная сумма нужна только для того чтобы на первом этапе показать какую сумму нужно собрать чтобы заказ можно было оформить, т.е. в примере это второе число (сдано/всего нужно собрать). Пример,

- минимальная сумма заказа 100000 (мы пишем 0/100000)

- кто-то добавил заявку на 50000, т.е. всё равно ещё нужно набрать заявок (ничего не поменялось 0/100000)

- кто-то добавил ещё одну заявку на 100000, т.е. итого заказ на сумму 150000 (0/150000). Т.е. пока автор не собрал эти 150000 он не сможет оформить заказ

- первый сдал деньги (50000/150000)

- второй сдал деньги (150000/150000)

> с наложением ограничений на действия пользователя стоит подождать

да, возможно.

**Comment by octocrux** [comment]
> кто-то добавил ещё одну заявку на 100000, т.е. итого заказ на сумму 150000 (0/150000).

Минимальная сумма заказа остается прежней - 100000. Просто теперь для успеха нам необходимо, чтобы деньги сдали все участники заказа. Менять минимальную сумму на 150000 - значит давать ложную информацию о поставщике.

**Comment by vitalk** [comment]
Так я не минимальную сумму показываю, а ту сколько нужно собрать `собранно`/`нужно собрать`. Просто на начальном этапе при создании заказа, нам нужно собрать минимальную сумму которую указывает поставщик, что я и пишу.

**Comment by vitalk** [comment]
Зачем людям знать минимальную сумму которую требует поставщик?
